version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wechat-postgres-staging
    environment:
      POSTGRES_DB: wechat_staging
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - wechat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d wechat_staging"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: ${DOCKER_HUB_REPO}-backend:${BACKEND_IMAGE_TAG}
    container_name: wechat-backend-staging
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DATABASE_URL: jdbc:postgresql://postgres:5432/wechat_staging
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      SERVER_PORT: 5000
    ports:
      - "5001:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wechat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    image: ${DOCKER_HUB_REPO}-frontend:${FRONTEND_IMAGE_TAG}
    container_name: wechat-frontend-staging
    environment:
      REACT_APP_API_BASE_URL: http://localhost:5001
      REACT_APP_WEBSOCKET_URL: ws://localhost:5001/ws
      REACT_APP_CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      REACT_APP_CLOUDINARY_UPLOAD_PRESET: ${CLOUDINARY_UPLOAD_PRESET}
      REACT_APP_ZEGO_APP_ID: ${ZEGO_APP_ID}
      REACT_APP_ZEGO_SERVER_SECRET: ${ZEGO_SERVER_SECRET}
    ports:
      - "3001:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - wechat-network

  redis:
    image: redis:7-alpine
    container_name: wechat-redis-staging
    ports:
      - "6380:6379"
    volumes:
      - redis_data_staging:/data
    networks:
      - wechat-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data_staging:
  redis_data_staging:

networks:
  wechat-network:
    driver: bridge
